FROM python:3.10-slim

WORKDIR /app

COPY ./webserver/webserver.py ./webserver/requirements.txt  /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 7080

CMD ["uvicorn", "webserver:app", "--host", "0.0.0.0", "--port", "7080"]